import { create } from 'zustand';
import { taskService } from '../services/taskService';
import useUserStore from './useUserStore';

const useTaskStore = create((set, get) => ({
  priorityQueue: [],
  allTasks: [],
  isLoading: false,
  error: null,

  // ── INIT ──
  fetchPriorityQueue: async () => {
    try {
      set({ isLoading: true, error: null });
      const user = useUserStore.getState().currentUserProfile;
      if (!user) return;
      
      const queue = await taskService.getPriorityQueue(user.id);
      set({ priorityQueue: queue });
    } catch (error) {
      console.error('Failed to fetch priority queue:', error);
      set({ error: error.message });
    } finally {
      set({ isLoading: false });
    }
  },

  fetchAllTasks: async (status = 'pending') => {
    try {
      set({ isLoading: true });
      const tasks = await taskService.getTasks(status);
      set({ allTasks: tasks });
    } catch (error) {
      console.error('Failed to fetch tasks:', error);
    } finally {
      set({ isLoading: false });
    }
  },

  // ── ACTIONS ──
  completeTask: async (taskId) => {
    try {
      // Optimistic update
      set(state => ({
        priorityQueue: state.priorityQueue.filter(t => t.task_id !== taskId),
        allTasks: state.allTasks.map(t => t.id === taskId ? { ...t, status: 'completed' } : t)
      }));
      
      await taskService.completeTask(taskId);
      
      // Re-fetch to get new tasks generated by DB triggers
      await get().fetchPriorityQueue();
    } catch (error) {
      console.error('Failed to complete task:', error);
      await get().fetchPriorityQueue(); // Revert on failure
    }
  },

  rescheduleTask: async (taskId, newDate) => {
    try {
      await taskService.rescheduleTask(taskId, newDate);
      await get().fetchPriorityQueue();
    } catch (error) {
      console.error('Failed to reschedule task:', error);
    }
  },

  createManualTask: async (leadId, title, type, priority, dueAt) => {
    try {
      const user = useUserStore.getState().currentUserProfile;
      if (!user) return;
      
      await taskService.createTask({
        lead_id: leadId,
        assigned_to: user.id,
        title,
        type,
        priority,
        due_at: dueAt,
        is_auto_generated: false
      });
      
      await get().fetchPriorityQueue();
    } catch (error) {
      console.error('Failed to create task:', error);
    }
  }
}));

export default useTaskStore;
